// ============================================================
// Caroud – Produktdaten
// Hier trägst du deine eigenen Produkte ein.
//   type:      "spray" | "baum" | "haenger" | "bundle"  (bestimmt das Platzhalter-Bild)
//   category:  "Duftsprays" | "Duftbäume" | "Duftanhänger" | "Bundles"
//   priceOld:  Streichpreis (null = kein Sale-Badge)
//   bestseller: true = erscheint in der Start-Ansicht "Bestseller"
//   notes:     Duftnoten, werden in der Detailansicht als Chips angezeigt
// ============================================================

const CATEGORIES = [
  { name: "Duftsprays", type: "spray", color: "#111111" },
  { name: "Duftbäume", type: "baum", color: "#2e5339" },
  { name: "Duftanhänger", type: "haenger", color: "#111111" },
  { name: "Bundles", type: "bundle", color: "#3b6ea5" },
];

const PRODUCTS = [
  {
    id: "spray-midnight",
    name: "Midnight Duftspray",
    type: "spray", category: "Duftsprays",
    color: "#111111", label: "Midnight",
    price: 24.99, priceOld: 34.99, bestseller: true,
    desc: "Dunkel, elegant, souverän. Midnight legt sich wie ein Maßanzug über deinen Innenraum – würzig-holzig mit einem Hauch Amber.",
    notes: ["Oud", "Amber", "Schwarzer Pfeffer"],
  },
  {
    id: "spray-cherry",
    name: "Cherry Rouge Duftspray",
    type: "spray", category: "Duftsprays",
    color: "#8e1b1b", label: "Cherry",
    price: 23.99, priceOld: 29.99, bestseller: true,
    desc: "Verspielt, aber mit Tiefe: dunkle Kirsche trifft auf Mandel und einen Schleier Vanille. Süß, ohne klebrig zu sein.",
    notes: ["Kirsche", "Mandel", "Vanille"],
  },
  {
    id: "spray-silver",
    name: "Silver Sky Duftspray",
    type: "spray", category: "Duftsprays",
    color: "#b9b9b9", label: "Silver",
    price: 24.99, priceOld: 34.99, bestseller: true,
    desc: "Frisch wie ein Neuwagen an einem klaren Morgen. Zitrus und Bergamotte auf einem kühlen, sauberen Moschus-Fundament.",
    notes: ["Bergamotte", "Zitrus", "Weißer Moschus"],
  },
  {
    id: "spray-vanilla",
    name: "Vanilla Cloud Duftspray",
    type: "spray", category: "Duftsprays",
    color: "#e8ddc4", label: "Vanilla",
    price: 22.99, priceOld: 29.99, bestseller: true,
    desc: "Cremige Vanille mit warmem Tonkabohnen-Herz – wie frisch gebackene Ruhe für lange Fahrten.",
    notes: ["Vanille", "Tonkabohne", "Sandelholz"],
  },
  {
    id: "spray-ocean",
    name: "Ocean Breeze Duftspray",
    type: "spray", category: "Duftsprays",
    color: "#2b7a8c", label: "Ocean",
    price: 23.99, priceOld: null, bestseller: false,
    desc: "Salzige Meeresluft, ein Hauch Minze und viel Weite. Der Duft für offene Fenster und Küstenstraßen.",
    notes: ["Meersalz", "Minze", "Treibholz"],
  },
  {
    id: "spray-golden",
    name: "Golden Hour Duftspray",
    type: "spray", category: "Duftsprays",
    color: "#c98a2c", label: "Golden",
    price: 24.99, priceOld: null, bestseller: false,
    desc: "Warmes Abendlicht als Duft: Safran, Honig und weiches Leder. Für Fahrten, die man nicht beenden will.",
    notes: ["Safran", "Honig", "Leder"],
  },
  {
    id: "haenger-midnight",
    name: "Midnight Duftanhänger",
    type: "haenger", category: "Duftanhänger",
    color: "#111111", label: "Midnight",
    price: 9.99, priceOld: 14.99, bestseller: true,
    desc: "Der Bestseller-Duft als schlichter Anhänger für den Rückspiegel – dezent im Look, präsent im Duft.",
    notes: ["Oud", "Amber", "Schwarzer Pfeffer"],
  },
  {
    id: "haenger-ocean",
    name: "Ocean Duftanhänger",
    type: "haenger", category: "Duftanhänger",
    color: "#2b7a8c", label: "Ocean",
    price: 9.99, priceOld: null, bestseller: true,
    desc: "Frische Meeresbrise für jeden Tag – hängt leicht, duftet lang.",
    notes: ["Meersalz", "Minze", "Treibholz"],
  },
  {
    id: "haenger-sunset",
    name: "Sunset Duftanhänger",
    type: "haenger", category: "Duftanhänger",
    color: "#c98a2c", label: "Sunset",
    price: 9.99, priceOld: null, bestseller: false,
    desc: "Goldene Stunde zum Aufhängen: warm, weich, unaufdringlich.",
    notes: ["Safran", "Honig", "Leder"],
  },
  {
    id: "haenger-cherry",
    name: "Cherry Duftanhänger",
    type: "haenger", category: "Duftanhänger",
    color: "#8e1b1b", label: "Cherry",
    price: 9.99, priceOld: 14.99, bestseller: true,
    desc: "Dunkle Kirsche und Vanille im Taschenformat – der süße Klassiker.",
    notes: ["Kirsche", "Mandel", "Vanille"],
  },
  {
    id: "haenger-forest",
    name: "Forest Duftanhänger",
    type: "haenger", category: "Duftanhänger",
    color: "#2e5339", label: "Forest",
    price: 9.99, priceOld: null, bestseller: false,
    desc: "Nadelwald nach dem Regen: grün, klar, erdig. Für alle, die es natürlich mögen.",
    notes: ["Zeder", "Kiefer", "Vetiver"],
  },
  {
    id: "haenger-blanc",
    name: "Blanc Duftanhänger",
    type: "haenger", category: "Duftanhänger",
    color: "#e8e4da", label: "Blanc",
    price: 9.99, priceOld: null, bestseller: false,
    desc: "Puristisch weiß, puristisch sauber: frische Wäsche und weißer Moschus.",
    notes: ["Baumwollblüte", "Weißer Moschus", "Iris"],
  },
  {
    id: "bundle-starter",
    name: "Starter Bundle",
    type: "bundle", category: "Bundles",
    color: "#111111", label: "Starter",
    price: 34.99, priceOld: 44.97, bestseller: true,
    desc: "Der perfekte Einstieg: 1 Duftspray deiner Wahl + 2 Duftanhänger. Spare gegenüber dem Einzelkauf.",
    notes: ["1× Spray", "2× Anhänger"],
  },
  {
    id: "bundle-signature",
    name: "Signature Bundle",
    type: "bundle", category: "Bundles",
    color: "#8e1b1b", label: "Signature",
    price: 54.99, priceOld: 69.95, bestseller: false,
    desc: "Für Sammler: 2 Duftsprays + 3 Duftanhänger – frei kombinierbar aus allen Düften.",
    notes: ["2× Spray", "3× Anhänger"],
  },
  {
    id: "baum-midnight",
    name: "Midnight Duftbaum",
    type: "baum", category: "Duftbäume",
    color: "#111111", label: "Midnight",
    price: 7.99, priceOld: null, bestseller: true,
    desc: "Der Signature-Duft als klassischer Duftbaum für den Rückspiegel – dunkel, elegant, langanhaltend.",
    notes: ["Oud", "Amber", "Schwarzer Pfeffer"],
  },
  {
    id: "baum-forest",
    name: "Forest Duftbaum",
    type: "baum", category: "Duftbäume",
    color: "#2e5339", label: "Forest",
    price: 7.99, priceOld: null, bestseller: false,
    desc: "Nadelwald nach dem Regen – grün, klar, erdig. Der Klassiker unter den Klassikern.",
    notes: ["Zeder", "Kiefer", "Vetiver"],
  },
  {
    id: "baum-cherry",
    name: "Cherry Duftbaum",
    type: "baum", category: "Duftbäume",
    color: "#8e1b1b", label: "Cherry",
    price: 7.99, priceOld: null, bestseller: true,
    desc: "Dunkle Kirsche und Vanille als Duftbaum – süß, ohne aufdringlich zu sein.",
    notes: ["Kirsche", "Mandel", "Vanille"],
  },
  {
    id: "baum-golden",
    name: "Golden Hour Duftbaum",
    type: "baum", category: "Duftbäume",
    color: "#c98a2c", label: "Golden",
    price: 7.99, priceOld: null, bestseller: false,
    desc: "Warmes Abendlicht zum Aufhängen – Safran, Honig und weiches Leder.",
    notes: ["Safran", "Honig", "Leder"],
  },
];
